site_name: 'Luminous Time Savers'
site_description: ''
site_author: 'Yann Duran'
site_url: 'https://luminous-software.solutions/time-savers'

repo_name: 'time-savers'
repo_url: 'https://github.com/luminous-software/time-savers'

copyright: 'Copyright (c) 2017 Luminous Software Solutions'

docs_dir: 'docs-source'
site_dir: 'docs'

theme:
    name: 'material'
    palette:
        primary: 'deep purple'
        accent: 'purple'
        custom_dir: 'docs-theme-overrides'
        favicon: 'assets/images/favicon.ico'
    feature:
        tabs: false

pages:
    - Enhancing Your Productivity: 'index.md'
    - How to Get Started: 'getting-started.md'
    - Change Log: 'changelog.md'
    - What's Coming: 'roadmap.md'
    - License: 'license.md'

extra:
    links:
        - https://luminous-software.solutions

extra_css:
    - assets/stylesheets/extra.css

extra_javascript:
    - assets/javascripts/extra.js

markdown_extensions:
    - markdown.extensions.tables
    - codehilite(css_class=code)
    - admonition
    - toc:
        permalink: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.magiclink:
        repo_url_shortener: true
        repo_url_shorthand: true
        social_url_shorthand: true
        provider: github
        user: luminous-software
        repo: pymdowntime-savers
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.tilde
    - pymdownx.superfences
    - pymdownx.snippets
