# project
site_name: 'Luminous Time Savers'
site_description: 'Documentation for Luminous Time Savers (Visual Studio extension)'
site_author: 'Yann Duran'
copyright: 'Copyright &copy Luminous Software Solutions'
site_url: 'https://luminous-software.solutions/time-savers'
site_dir: 'docs'
docs_dir: 'docs-source'
dev_addr: '127.0.0.1:8004'

# repository
#repo_name: 'time-savers'
#repo_url: 'https://github.com/luminous-software/time-savers'
remote_branch: 'master'
remote_name: 'origin'

# configuration
theme:
    name: 'material'
    language: 'en'
    palette:
        primary: 'deep purple'
        accent: 'purple'
    custom_dir: 'docs-theme-overrides'
    favicon: 'assets/images/favicon.ico'
    feature:
        tabs: true
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo:
        icon: 'lightbulb_outline'

# layout
pages:
    - Home:
        - Why Luminous Time Savers?: 'index.md'
        - How to Get Started: 'getting-started.md'
        - Features: 'features.md'
        - Change Log: 'changelog.md'
        - What's Coming: 'roadmap.md'
        #- License: 'license.md'
#    - Luminous Software Solutions:
#        - Luminous Software Website: 'website.md' #'https://luminous-software.solutions'
#        - Luminous Software Blog: 'blog.md' #'https://luminous-software.solutions/blog'

#    - Features:
#        - Features: 'features.md'

#        - General Features: 'features/general.md'
#        - Solution Features: 'features/solution.md'
#        - Project Features: 'features/project.md'
#        - Build Features: 'features/build.md'
#        - Log Features: 'features/logs.md'
#        - Visual Studio Features: 'features/vs.md'

# customisation
extra:
    version: ''
    discus: ''
    links:
        - https://luminous-software.solutions
    social:
        - type: 'twitter'
        - link: 'https://twitter.com/lumiinus'
        - type: 'linkedin'
        - link: 'https://linkedin.com/in/yannduran'
    repo_icon: ''

extra_css:
    - assets/stylesheets/extra.css

extra_javascript:
    - assets/javascripts/extra.js

# extensions
markdown_extensions:
    - markdown.extensions.tables
    - codehilite(css_class=code)
    - admonition
    - toc:
        permalink: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.magiclink:
        repo_url_shortener: true
        repo_url_shorthand: true
        social_url_shorthand: true
        provider: github
        user: luminous-software
        repo: time-savers
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.tilde
    - pymdownx.superfences
    - pymdownx.snippets
